% Author: Min Kim
% Date: 11/22/21
% FileName: inputs.m
% Sample inputs and instruction of how to use clsTruss

close all;
clear;
clc;

% Set up ploblem geometry
node = [ ...
        0, 0; ...
        2, 0; ...
        4, 0; ...
        6, 0; ...
        4, 1; ...
        2, 2; ...
        0, 3; ...
    ];
element = [ ...
            1, 2; ...
            1, 6; ...
            2, 3; ...
            2, 7; ...
            2, 6; ...
            2, 5; ...
            3, 5; ...
            3, 4; ...
            4, 5; ...
            5, 6; ...
            6, 7; ...
        ];
E = 6.024e11; % Pa
A = pi * (21.3e-3)^2; % m^2

F = [ ...
        5, 0, -2e6; ...
        6, 0, -2e3; ...
        4, 0, -2e3
    ]; % N
    % Displacement value construction, the format is same as above
dispVec = [ ...
            1, 0, 0; ...
            7, 0, 0; ...
        ];

tr = clsTruss(node, element, E, A, F, dispVec);
tr.calcAll(false);
tr.save2xlsx();
tr.pltTruss(true);