close all;
clear;
clc;

node = [ ...
        0, 0; ...
        20, 0; ...
        20, 15; ...
        0, 15; ...
    ];
elem = [ ...
        1, 2; ...
        1, 3; ...
        2, 4; ...
        2, 3; ...
        3, 4; ...
        1, 4; ...
    ];
E = 1e6; A = 1;
F = [ ...
    2, 0, 1e3; ...
    3, 0, 1e3; ...
    ];
vecU = [ ...
        1, 0, 0; ...
        4, 0, 0; ...
    ];
tr = clsTruss(node, elem, E, A, F, vecU);
tr.calcAll(true);
tr.pltTruss(false);
