close all;
clear;
clc;

node = [...
        -36, 0, 0; ...
        -144, 72, 0; ...
        -144, -72, 0; ...
        0, 0, 144
    ];
elements = [...
            1, 4; ...
            2, 4; ...
            3, 4; ...
            2, 3
        ];
F = [4, 0, 0, -4e3];
vecU = [ ...
        1, 0, 0, 0; ...
        2, 0, 0, 0; ...
        3, 0, 0, 0; ...
    ];
E = 30e6; A = 4;
tr = clsTruss(node, elements, E, A, F, vecU);
tr.pltTruss(false);
tr.calcAll(true);
tr.pltTruss(false);
